### PR TITLE
Rename langcheck.eval to langcheck.metrics

### LINKED ISSUE #5: Rename langcheck.eval to langcheck.metrics
`eval` is a built-in global function in Python.

### PR DESCRIPTION
**Pull request by liwii**
Resolves #5.

### CODE REVIEW

**Comment by kennysong** [comment]
Awesome! Read through the diffs and they look good to me. I noticed that we need to fix the underline of some `.rst` headings since Sphinx prints out a few warnings when building the new docs. (You can ignore the EvalValue warnings)

```
vscode ➜ /workspaces/langcheck (rename-eval) $ make -C docs clean html
make: Entering directory '/workspaces/langcheck/docs'
Removing everything under '_build'...
Running Sphinx v6.2.1
making output directory... done
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'colon_fence'}, disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 20 source files that are out of date
updating environment: [new config] 20 added, 0 changed, 0 removed
reading sources... [100%] quickstart                                                                                                                                     
/workspaces/langcheck/docs/langcheck.metrics.rst:5: WARNING: Title underline too short.

langcheck.metrics
==============
/workspaces/langcheck/docs/langcheck.metrics.en.rst:5: WARNING: Title underline too short.

langcheck.metrics.en
=================
/workspaces/langcheck/docs/langcheck.metrics.en.reference_based_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.en.reference\_based\_text\_quality
=================================================
/workspaces/langcheck/docs/langcheck.metrics.en.reference_free_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.en.reference\_free\_text\_quality
================================================
/workspaces/langcheck/docs/langcheck.metrics.en.source_based_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.en.source\_based\_text\_quality
==============================================
/workspaces/langcheck/docs/langcheck.metrics.eval_value.rst:3: WARNING: Title underline too short.

langcheck.metrics.eval\_value
==========================
/workspaces/langcheck/docs/langcheck.metrics.ja.rst:5: WARNING: Title underline too short.

langcheck.metrics.ja
=================
/workspaces/langcheck/docs/langcheck.metrics.ja.reference_based_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.ja.reference\_based\_text\_quality
=================================================
/workspaces/langcheck/docs/langcheck.metrics.ja.reference_free_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.ja.reference\_free\_text\_quality
================================================
/workspaces/langcheck/docs/langcheck.metrics.reference_based_text_quality.rst:3: WARNING: Title underline too short.

langcheck.metrics.reference\_based\_text\_quality
==============================================
/workspaces/langcheck/docs/langcheck.metrics.text_structure.rst:3: WARNING: Title underline too short.

langcheck.metrics.text\_structure
==============================
looking for now-outdated files... none found
```

**Comment by kennysong** [comment]
Also, I wonder if we should rename EvalValue to MetricValue as well now?

**Comment by liwii** [comment]
Oh didn't even know that the length of `===` matters.

Updated the docs. Also renamed `EvalValue` to `MetricValue`.

**Comment by kennysong** [comment]
Yeah, RST is a very picky text format. It's whitespace sensitive too 😵‍💫

LGTM after fixing the flake8 issues!

**Review by kennysong — APPROVED** [review]

**Comment by liwii** [comment]
Thanks!!

**Pull request merged**
