### PR TITLE
Chinese Support with Model Config Manager

### PR DESCRIPTION
**Pull request by Vela-zz**
1. Chinese support align with latest ja/en branch updates.
   - [x] add hanlp tokenizer.
   - [x] fully support reference based metrics.
   - [x] support sentiment and toxicity in reference free metrics, fluency not supported yet. prompt  not leveraged.
   - [x] support source based metrics. prompt not leveraged.
 
2. add a model manager class
   - [x] manager model settings by a yaml config file, can pin model/tokenizer to a fixed version.
   - [x] check model availability, fetch the corresponding model when needed.
   - [x] print out current model in use.

### CODE REVIEW

**Review by yosukehigashi — APPROVED** [review]
Did a final round of testing and confirmed that everything is working as expected. Thanks @Vela-zz for this massive contribution! I'll merge this once tests pass again

**Comment by yosukehigashi** [comment]
> Did a final round of testing and confirmed that everything is working as expected. Thanks @Vela-zz for this massive contribution! I'll merge this once tests pass again

Oh actually they already passed - merging now!

**Comment by Vela-zz** [comment]
> > Did a final round of testing and confirmed that everything is working as expected. Thanks @Vela-zz for this massive contribution! I'll merge this once tests pass again
> 
> Oh actually they already passed - merging now!

Thanks for your review ! it seems because I use request lib in check_model_availability, and set timeout to 1 second, so sometimes the test become failure if internet traffic jammed.

**Comment by yosukehigashi** [comment]
> > > Did a final round of testing and confirmed that everything is working as expected. Thanks @Vela-zz for this massive contribution! I'll merge this once tests pass again
> > 
> > 
> > Oh actually they already passed - merging now!
> 
> @yosukehigashi Thanks for your review ! it seems because I use request lib in check_model_availability, and set timeout to 1 second, so sometimes the test become failure if internet traffic jammed.

Yeah I saw that, but it was due to HuggingFace being completely down. It might be good to remove this so that our tests are not dependent on external factors, but I didn't think it was a blocker for merging this :)

**Pull request merged**
