### PR TITLE
Add discord badges to README files

### PR DESCRIPTION
**Pull request by liwii**
Screenshot 2023-10-19 at 21 59 53

### CODE REVIEW

**Comment by kennysong** [comment]
Ah nice! Can we change the server name to "LangCheck"? Otherwise LGTM. I'm assuming the invite link you generated doesn't have an expiration date.

**Review by kennysong — APPROVED** [review]

**Comment by liwii** [comment]
Updated the server name.

I reused the invitation link you generated, does that have the expiration date?

**Comment by kennysong** [comment]
Yeah, I think the one I generated in the issue expires in 7 days

**Comment by liwii** [comment]
Updated the link to one that does not expire.

**Pull request merged**
