### PR TITLE
Remove the dependency on Detoxify

### PR DESCRIPTION
**Pull request by yosukehigashi**
Fixes https://github.com/citadel-ai/langcheck/issues/59

Starting in [0.5.1](https://github.com/unitaryai/detoxify/releases/tag/v0.5.1), Detoxify started pinnng the version of transformers. This forces v4.22.1 to be installed, which leads to an old version of `tokenizers` getting installed, which leads to https://github.com/citadel-ai/langcheck/issues/59.

This PR removes the dependency on the Detoxify repo, since we just need to download the model weights and load it up as a HF model.

Confirmed that installing langcheck was failing before on python 3.10 macos, and after this change installing langcheck succeeds.

### CODE REVIEW

**Comment by Vela-zz** [comment]
> tests are failing.. 🤨

Ja test failing because https://huggingface.co/line-corporation/line-distilbert-base-japanese/discussions/3

**Comment by yosukehigashi** [comment]
> > tests are failing.. 🤨
> 
> when these dependence update appilied, transformer version == 4.35.2 Ja test failing because https://huggingface.co/line-corporation/line-distilbert-base-japanese/discussions/3

Ah nice, thanks for the link! cc @liwii who's looking into a fix for this

**Comment by Vela-zz** [comment]
change detoxity this part would let the model loaded normally.

```
  def get_model_and_tokenizer(
      model_type, model_name, tokenizer_name, num_classes, state_dict, huggingface_config_path=None
  ):
      # print(model_type)
      # print(model_name)
      # print(tokenizer_name)
      model_class = getattr(transformers, model_name)
      model = model_class.from_pretrained(
         #Here
          pretrained_model_name_or_path = None -> pretrained_model_name_or_path = model_type
          config=huggingface_config_path or model_type,
          num_labels=num_classes,
          state_dict=state_dict,
          local_files_only=huggingface_config_path is not None,
      )
      tokenizer = getattr(transformers, tokenizer_name).from_pretrained(
          huggingface_config_path or model_type,
          local_files_only=huggingface_config_path is not None,
          # TODO: may be needed to let it work with Kaggle competition
          # model_max_length=512,
      )
  
      return model, tokenizer
```

**Comment by yosukehigashi** [comment]
> change detoxity this part would let the model loaded normally.
> 
> ```
>   def get_model_and_tokenizer(
>       model_type, model_name, tokenizer_name, num_classes, state_dict, huggingface_config_path=None
>   ):
>       # print(model_type)
>       # print(model_name)
>       # print(tokenizer_name)
>       model_class = getattr(transformers, model_name)
>       model = model_class.from_pretrained(
>          #Here
>           pretrained_model_name_or_path = None -> pretrained_model_name_or_path = model_type
>           config=huggingface_config_path or model_type,
>           num_labels=num_classes,
>           state_dict=state_dict,
>           local_files_only=huggingface_config_path is not None,
>       )
>       tokenizer = getattr(transformers, tokenizer_name).from_pretrained(
>           huggingface_config_path or model_type,
>           local_files_only=huggingface_config_path is not None,
>           # TODO: may be needed to let it work with Kaggle competition
>           # model_max_length=512,
>       )
>   
>       return model, tokenizer
> ```

Nice, thanks! I might try and submit a PR to detoxify directly (or if you want to instead, of course please go ahead!) and then we can replace our constraints with just `'detoxify >= 0.5.2' # assuming fix goes in to 0.5.2`.

Either way, we still need to fix the LINE tokenizer issue, if we want to get rid of the pin to transformers v4.22.1 and fix #59)

**Comment by yosukehigashi** [comment]
> Nice, thanks! I might try and submit a PR to detoxify directly (or if you want to instead, of course please go ahead!) and then we can replace our constraints with just `'detoxify >= 0.5.2' # assuming fix goes in to 0.5.2`.

Actually, maybe we can just write the code to download the Detoxify model directly from HF without adding the github repo as a dependency (maybe this is what @Vela-zz was suggesting?). I'll give this a shot.

**Comment by Vela-zz** [comment]
> > Nice, thanks! I might try and submit a PR to detoxify directly (or if you want to instead, of course please go ahead!) and then we can replace our constraints with just `'detoxify >= 0.5.2' # assuming fix goes in to 0.5.2`.
> 
> Actually, maybe we can just write the code to download the Detoxify model directly from HF without adding the github repo as a dependency (maybe this is what @Vela-zz was suggesting?). I'll give this a shot.

Yes, I saw the detoxity library. I think download the model weight and use new transformer API seems better.

**Comment by liwii** [comment]
Made a [fork repo](https://huggingface.co/liwii/line-distilbert-base-japanese-fork/blob/main/distilbert_japanese_tokenizer.py) of the `line-distilbert-base-japanese` and fixed the tokenizer issue there. I also made a [PR](https://huggingface.co/line-corporation/line-distilbert-base-japanese/discussions/4), but let's use the working tokenizer in the fork for a while.

Thanks for clarifying the issue, @Vela-zz !!

**Comment by liwii** [comment]
Actually the PR was merged in amazing speed so we do not need to rely on my fork 😅

**Comment by kennysong** [comment]
Wow that's impressively fast!

**Comment by yosukehigashi** [comment]
Thanks for the fixes and suggestions! I removed the dependency on `detoxify` as @Vela-zz suggested so we're now installing the latest transformers version (v4.35.2), and thanks to Koki's PR the Japanese metrics work on that now.

**Comment by kennysong** [comment]
Thanks!! Changes LGTM and confirmed it installs properly on Python 3.10 on macOS now.

**Pull request merged**
